language: cpp
compiler: gcc
script:
   - sudo apt-get update
   - sudo apt-get install gcc-4.8
   - sudo apt-get install cmake
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50

